// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeuroYogic.Infrastructure.Persistence;

#nullable disable

namespace NeuroYogic.Infrastructure.Migrations
{
    [DbContext(typeof(NeuroYogicDbContext))]
    [Migration("20260712072417_AddClientsAndSessionLink")]
    partial class AddClientsAndSessionLink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("NeuroYogic.Domain.Entities.ActivityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Archived")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("ActivityTypes");
                });

            modelBuilder.Entity("NeuroYogic.Domain.Entities.AnalysisRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AlphaRelative")
                        .HasColumnType("REAL");

                    b.Property<double?>("BloodOxygen")
                        .HasColumnType("REAL");

                    b.Property<string>("ChittaBhumi")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<double>("ChittaConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("ContemplativeDepth")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double>("ContemplativeDepthScore")
                        .HasColumnType("REAL");

                    b.Property<double>("Faa")
                        .HasColumnType("REAL");

                    b.Property<double>("GammaRelative")
                        .HasColumnType("REAL");

                    b.Property<double?>("HeartRate")
                        .HasColumnType("REAL");

                    b.Property<double>("HighBetaRelative")
                        .HasColumnType("REAL");

                    b.Property<double>("Plv")
                        .HasColumnType("REAL");

                    b.Property<double>("Rajas")
                        .HasColumnType("REAL");

                    b.Property<double>("Sattva")
                        .HasColumnType("REAL");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Swara")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<double>("Tamas")
                        .HasColumnType("REAL");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<double>("VrittiIndex")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Timestamp");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("NeuroYogic.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Archived")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Goal")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PracticingSince")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Protocol")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProtocolSince")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("UserId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("NeuroYogic.Domain.Entities.DepthProbe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepthRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Timestamp");

                    b.ToTable("Probes");
                });

            modelBuilder.Entity("NeuroYogic.Domain.Entities.MeditationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Activity")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EndedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpochCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("MeanDepthScore")
                        .HasColumnType("REAL");

                    b.Property<double>("MeanRajas")
                        .HasColumnType("REAL");

                    b.Property<double>("MeanSattva")
                        .HasColumnType("REAL");

                    b.Property<double>("MeanTamas")
                        .HasColumnType("REAL");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("UserId", "StartedAt");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("NeuroYogic.Domain.Entities.SessionWatchToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RedeemedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RedeemedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RevokedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("SessionId", "ExpiresAt");

                    b.ToTable("WatchTokens");
                });

            modelBuilder.Entity("NeuroYogic.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NeuroYogic.Domain.Entities.AnalysisRecord", b =>
                {
                    b.HasOne("NeuroYogic.Domain.Entities.MeditationSession", "Session")
                        .WithMany("Records")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("NeuroYogic.Domain.Entities.DepthProbe", b =>
                {
                    b.HasOne("NeuroYogic.Domain.Entities.MeditationSession", "Session")
                        .WithMany("Probes")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("NeuroYogic.Domain.Entities.MeditationSession", b =>
                {
                    b.HasOne("NeuroYogic.Domain.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeuroYogic.Domain.Entities.SessionWatchToken", b =>
                {
                    b.HasOne("NeuroYogic.Domain.Entities.MeditationSession", "Session")
                        .WithMany("WatchTokens")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("NeuroYogic.Domain.Entities.MeditationSession", b =>
                {
                    b.Navigation("Probes");

                    b.Navigation("Records");

                    b.Navigation("WatchTokens");
                });

            modelBuilder.Entity("NeuroYogic.Domain.Entities.User", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
